title: Improving Neuroimaging Data for Sharing
email: robert.oostenveld@donders.ru.nl
description: INDoS COST Action
baseurl: ""
url: "https://indos-costaction.github.io"
logo: /assets/images/logo-v5.png

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Navigation
header_pages:
  - index.md
  - collaborators.md
  - workgroups.md
  - contact.md

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - STRUCTURE.md
  - LICENSE.md
